OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: CertifiedCompanies
    Domain: certifiedCompanies.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Certifiers
    Domain: certifiers.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: TestOrg
    Domain: testOrg.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1